#import <Foundation/NSObject.h>

@class NSString;
@class NSAttributedString;
@class SCKSourceLocation;
@class NSMutableArray;
@class NSMutableDictionary;

/**
 * SCKProgramComponent is an abstract class representing properties of some
 * component of a program.  This includes classes, functions, methods, and so
 * on.
 *
 * Program components in SourceCodeKit can be obtained both by runtime
 * introspection and by parsing source code.  
 */
@interface SCKProgramComponent : NSObject
/**
 * The name of this program component.
 */
@property (nonatomic, retain) NSString *name;
/**
 * The location where the component is defined, if visible.  
 */
@property (nonatomic, retain) SCKSourceLocation *definition;
/**
 * The location where the component is declared, if visible.  
 */
@property (nonatomic, retain) SCKSourceLocation *declaration;
/**
 * Documentation associated with this object.  This may be generated by an IDE,
 * extracted from headers, or read from some external source.
 */
@property (nonatomic, retain) NSAttributedString *documentation;
/**
 * The parent of this component.  
 */
@property (nonatomic, assign) SCKProgramComponent *parent;
@end

@interface SCKBundle : SCKProgramComponent
/**
 * All of the public symbols exported by the bundle.
 */
@property (nonatomic, retain) NSMutableArray *classes;
@property (nonatomic, retain) NSMutableArray *functions;
@end

@interface SCKClass : SCKProgramComponent
@property (nonatomic, assign) SCKClass *superclass;
@property (nonatomic, retain, readonly) NSMutableArray *subclasses;
@property (nonatomic, retain, readonly) NSMutableDictionary *categories;
@property (nonatomic, retain, readonly) NSMutableDictionary *methods;
@property (nonatomic, retain, readonly) NSMutableArray *ivars;
- (id) initWithClass: (Class)cls;
@end

@interface SCKCategory : SCKProgramComponent
@property (nonatomic, retain, readonly) NSMutableDictionary *methods;
@end

@interface SCKMethod : SCKProgramComponent
@property (nonatomic) BOOL isClassMethod;
@property (nonatomic, retain) NSString *type;
@end

@interface SCKIvar : SCKProgramComponent
@property (nonatomic, retain) NSString *type;
@end

@interface SCKFunction : SCKProgramComponent
@end
